apiVersion: v1
kind: Secret
metadata:
  name: credentials-secret
type: Opaque
stringData:
  username: import-user-sample
  passwordHash: "" # The user will not have a valid password. Login attempts with any password will be rejected
  password: anythingreally # This value will be ignored, because `passwordHash` takes precedence
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: import-user-sample
spec:
  tags:
  - management # available tags are 'management', 'policymaker', 'monitoring' and 'administrator'
  - policymaker
  rabbitmqClusterReference:
    name: test # rabbitmqCluster must exist in the same namespace as this resource
  importCredentialsSecret:
    name: credentials-secret
